name: Openwrt autobuild test

on:
  #schedule:
  #  - cron: 0 08 * * *
  #  
  push:
    paths:
      - '.github/workflows/x86.yml'

  #   branches: 
  #     - master
  #watch:
  #  types: [started]
env:
  SSH_ACTIONS: true

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: 清理和安装编译环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk

      - name: 检出源码
        run: |
          git clone https://github.com/openwrt/openwrt.git
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: SSH connection to Actions
        uses: caoshijun/debugger-action@master
        if: env.SSH_ACTIONS == 'true' || contains(github.event.action, 'ssh')
          

      - name: 下载依赖包
        run: |
          cd openwrt
          make download -j8
          find dl -size -1024c -exec rm -f {} \;
          
      - name: 编译
        run: |
          cd openwrt
          make -s -j$(($(nproc) + 1)) || make -j1 V=s
 
      - name: 打包
        run: |
          find ./openwrt/bin/targets/ -type d -name "packages" | xargs rm -rf {}
          mkdir -p ./artifact/
          cp -ar ./openwrt/bin/targets/* ./artifact/
          cp ./openwrt/.config  ./artifact/

      - name: 上传
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt_x86_64
          path: ./artifact/
